### ISSUE TITLE
Solution_Error_Modeling_Fundamentals_Creating_More Nodes

### ISSUE THREAD

**Issue by NikkiBausch** [neo4j-graphacademy/courses#46]
Understandably, I am trying to come up with the solution to this on my own. HOWEVER, I'm a bit stumped as what I have tried so far isn't working. So I checked the solution--and am getting this instead of the solution: 

include::../solution.cypher

URL for clarity: https://graphacademy.neo4j.com/courses/modeling-fundamentals/2-defining-nodes/4-c-creating-nodes/
Screenshot below for further clarity: 
![grafik](https://user-images.githubusercontent.com/41345938/204141413-be95601c-690a-43af-9379-8e1c574d9501.png)

This was the solution I submitted: 
MERGE (:Person {userId: 534, name:'Sandy Jones'})
MERGE (:Person {userId: 105, name:'Clinton Spencer'})

I have this result, but I'm wondering if it's not taking it because it isn't matching the value for the solution: 
![grafik](https://user-images.githubusercontent.com/41345938/204143152-26e82f9d-b2ef-476e-993d-9a508d6a3b16.png)

**Comment by ElaineRosenberg** [comment]
For this Challenge, you should have created User nodes, not Person nodes. Your MERGE is correct, except for the label you used, which was Person.
